name: med-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pip:
      - fastapi==0.115.0
      - uvicorn[standard]==0.30.6
      - pydantic==2.9.2
      - pydantic-settings==2.4.0
      - python-dotenv==1.0.1
      - boto3==1.35.19
      - botocore==1.35.19
      - pydub==0.25.1
      - requests==2.32.3
      - openai==1.51.0
      - httpx==0.27.2
